added main page, navbar, language switcher, sass
AleksKostin/t-ende-landing-page pull request #1
Opened 2023-09-07 00:31 UTC by AleksKostin

Добавил MainPage с масштабируемым фоном, анимацию заголовка и текста после загрузки страницы, анимацию стрелки скролла (анимацию смены заголовка нужно сделать). Подключил препроцессор sass для проекта

2023-09-07 08:34 UTC, DmitriiNazimov requested changes
В целом мне понравилось. Написано аккуратно. Серьезных замечаний нет.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/app/styles/index.scss
> +  padding-right: 15px;
Лучше не прописывать отступы в пикселях, а использовать либо переменные, либо rem.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/assets/pictures/mainPageWoman.png
Картинка весит 2.1 мб - это тумач. Надо подготовить изображение для веб. Можно настроить сборщик чтобы он сжимал картинку, но надо смотреть насколько это эффективно будет. Хотя может уже настроено, пока не проверял.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/LangSwitcher/LangSwitcher.jsx
> +    <div className="lng-switcher">
Может все-таки lang, а не lng? Желательно чтобы нейминг был "говорящим".

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/LangSwitcher/LangSwitcher.scss
> +}
Тут в конце файла не хватает пустой строки. Настрой eslint или IDE чтобы автоматически добавляли пустую строку в конец файла, если ее там нет. Наличие пустой строки важно для корректной работы GIT. Не знаю видно тебе или нет, но мне в PR показывает красный значок в этом месте - ругается что нет пустой строки.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/app/styles/variables/global.scss
> +  --font-mon-m: var(--font-mon-size-m) / var(--font-mon-line-m) var(--font-family-main);
Тут нужны комментарии что происходит и зачем. Не очевидно. Я такого не видел :)

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/LangSwitcher/LangSwitcher.scss
> +  font: var(--font-mon-medium-m);
Тоже к вопросу о нейминге. Мне кажется не стоит экономить на словах и сделать более понятно.

--font-mon-medium-m -> --font-monterrey-weight_medium-m

Или типа того. Смысл в том, что непонятно что такое mon. И не совсем понятно что такое medium.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.jsx
> +  const { t } = useTranslation();
Давай все-таки translate, а не t.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.jsx
> +        <div className="navbar-conteiner">
Опечатка в слова container

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.jsx
> +            <button
Тег button семантически не подходит. Нужен тег A.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +#navbar {
id - deprecated. Используй классы. 
https://frontender.info/when-using-ids-can-be-a-pain-in-the-class/

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +  left: 0;
left: 0 тут разве будет работать? Элемент ведь не позиционирован.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +  background: none;
А вот если бы использовал тег А, то не пришлось бы писать лишние стили чтобы убрать стилизацию как у кнопок.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +  margin-left: 70px;
Может размер отступа в переменную и сделать одинаковым с navbar-link?

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +@media (width < 1020px) {
Почему 1020, а не 1024?

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +    margin-left: 10px;
Отступы в переменную. И здесь наверное можно объединить в одно правило: margin: 0 10px; (вместо 10px - переменная)

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/data/data.json
> +}
Пустой строки внизу не хватает.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.jsx
> +  const { t } = useTranslation();
Лучше translate

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.jsx
> +import arrow from '../../assets/icons/arrow.svg';
Задание со звездочкой: настроить импорты так, чтобы убрать ../../, а можно было так:
@assets/icons/arrow.svg 
или
assets/icons/arrow.svg

Это не обязательно, но на собесе будет прикольно если сможешь поддержать разговор на эту тему.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.jsx
> +    const timer = setTimeout(() => setIsLoaded(() => true), 200);
Почему 200? Это магическое число? 

Магическими называют такие числа в коде, смысл которых понятен только написавшему их программисту. 

Магия - это не круто.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.jsx
> +    <div id="main-page">
id deprecated.

2023-09-07 08:34 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.scss
> +  animation: jump 0.8s ease 1.5s infinite alternate;
👍

2023-09-11 13:33 UTC, DmitriiNazimov requested changes

2023-09-11 13:33 UTC, DmitriiNazimov commented on jsconfig.json
> +}
В JSON файлах еще осталась проблема отсутствия пустой строки в конце.

2023-09-11 13:33 UTC, DmitriiNazimov commented on src/components/LangSwitcher/LangSwitcher.jsx
> +      <button type="button" className="lang-btn lang-link">
lang-link - лишний класс. Это можно сделать нативными средствами типа last-child. Я отрефакторил header__link, можешь сделать по аналогии.

2023-09-11 13:33 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.jsx
>                {data ? data.paragraph : 'Loading...'}
"Loading" и "scroll to services" надо бы добавить интернационализацию.

2023-09-14 00:04 UTC, AleksKostin commented
feat: add MainPage, Navbar, LangSwitcher; configure i18n, sass

2023-09-14 00:06 UTC, merged