refactor: design issues
AleksKostin/t-ende-landing-page pull request #11
Opened 2024-01-11 00:32 UTC by AleksKostin

2024-01-11 07:59 UTC, DmitriiNazimov approved these changes

2024-01-12 11:24 UTC, DmitriiNazimov approved these changes

2024-01-13 20:33 UTC, DmitriiNazimov requested changes

2024-01-13 20:33 UTC, DmitriiNazimov commented on package.json
> +    "react-helmet": "^6.1.0",
Версию забыл зафиксировать.

2024-01-13 20:33 UTC, DmitriiNazimov commented on src/pages/ArticleDetailsPage/ArticleDetailsPage.jsx
> +        <title>{`${t('interestingTurkey')}. ${currentArticle.title}`}</title>
Тут хватит только ${currentArticle.title}

2024-01-13 20:33 UTC, DmitriiNazimov commented on src/pages/ServiceDetailsPage/ServiceDetailsPage.jsx
> +        <title>{`${currentService.title}. ${currentService['title-article']}`}</title>
Тут хватит только currentService['title-article']

2024-01-13 20:33 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.jsx
> +        <title>{t('headerTitleMain')}</title>
Есть проблема с тайтлами: сначала показывается title = "Document" и через долю секунды подгружается корректный тайтл. Я так понимаю document подгружается из index.html и показывается до момента пока JS не подгрузится. 
Исправить это вероятно никак. Но можно замаскировать. Думаю стоит очистить содержимое тега тайтл и тогда не будет "мигания" тайтла.
Либо возможно лучше установить корректный татйл по умолчанию, но хз какой брать. На русском, или на английском, такой же как на главной или другой? 
Можешь погуглить, потом расскажешь. Ну или просто очистить содержимое тега тайтл.

2024-01-20 15:34 UTC, DmitriiNazimov requested changes

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/index.jsx
> +let root = document.getElementById('root');
```javascript
const rootElem = document.getElementById('root');
let root = null;

if (isRenderingOnClient) {
  root = ReactDOM.hydrateRoot(rootElem);
} else if (root) {
  root = ReactDOM.createRoot(rootElem);
  i18n.changeLanguage(Locales.ru);
} else {
// обработать ситуацию если root не был создан.
}
```

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/pages/ArticleDetailsPage/ArticleDetailsPage.jsx
> +    return <Navigate to="/*" state={{ originalUrl: location.pathname }} replace />;
Тут явно что-то идет не так. Это должно решаться на уровне роутера.

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/components/LangSwitcher/data.js
> +export const clientLang = document.getElementById('root')
```javascript
const isRenderingOnClient = document.getElementById('root')?.hasChildNodes();

export const clientLang = isRenderingOnClient ? (navigator.language || navigator.userLanguage).slice(0, 2) : Locales.ru;

```
isRenderingOnClient по хорошему должно быть глобальной переменной, чтобы в src/index.jsx не создавать заново. Соответственно объявляться должна в более подходящем месте, чем LangSwitcher/data

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +import routs from 'config/routeConfig/routeConfig';
routes, а не routs. Опечатка.

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +      window.history.replaceState({}, '', originalUrl);
Не понимаю зачем это. Я не говорю что это неправильно, просто нужна пояснительная бригада )

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +const NotFoundPage = ({ footerHeight }) => {
Чет я не понимаю почему у нас высота футера приходит как проп из вне.

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +    const listener = () => setIsMobile(media.matches);
resizeListener

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +  const heightNotFoundPage = `calc(
Что-то очень странное происходит с высотой в этом компоненте.

2024-01-20 15:34 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.scss
> +  .not-found__404 {
Может not-found__title?

2024-01-20 21:55 UTC, AleksKostin commented on src/pages/ArticleDetailsPage/ArticleDetailsPage.jsx
> +    return <Navigate to="/*" state={{ originalUrl: location.pathname }} replace />;
На уровне роутера решается только проверка на отсутствие path, которые не указаны в Routes, с помощью path='*'. А здесь же происходит редирект на 404, если id статьи не существует.

2024-01-20 21:55 UTC, AleksKostin commented on src/components/LangSwitcher/data.js
> +export const clientLang = document.getElementById('root')
Сделаю

2024-01-20 21:56 UTC, AleksKostin commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +import routs from 'config/routeConfig/routeConfig';
Очепятка, с кем не бывает)

2024-01-20 22:01 UTC, AleksKostin commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +      window.history.replaceState({}, '', originalUrl);
Если я делаю редирект на 404 из какой либо не существующей статьи или услуги, то урл будет такой - ".../landing/article/1223/*" и чтобы убрать эту звездочку из урла, я с помощью хука useLocation и свойства state, в которое я положил еще в компонете статьи путь без звездочки , меняю урл на корректный

2024-01-20 22:05 UTC, AleksKostin commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +const NotFoundPage = ({ footerHeight }) => {
хук useFooterHeight использует в своем коде ref для ссылки на футер, и этот ref футеру я могу присвоить лишь в корневом компоненте приложения App, поэтому чтобы NotFoundPage смог использовать динамически вычисляемую высоту футера я прокидываю ее пропсом

2024-01-20 22:05 UTC, AleksKostin commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +    const listener = () => setIsMobile(media.matches);
Сделаю

2024-01-20 22:10 UTC, AleksKostin commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +  const heightNotFoundPage = `calc(
Я решил на 404 странице сохранить и Navbar и Footer, при этом хотел чтобы 404 страница имела height=100vh без скролла. Для этого я с помощью js вычисляю высоту вычитая из нее высоту Navbara фиксированную с помощью переменных css и высоту футера получаемую из пропса footerHeight

2024-01-20 22:11 UTC, AleksKostin commented on src/pages/NotFoundPage/NotFoundPage.scss
> +  .not-found__404 {
Да, логично

2024-01-20 22:48 UTC, DmitriiNazimov commented on src/pages/ArticleDetailsPage/ArticleDetailsPage.jsx
> +    return <Navigate to="/*" state={{ originalUrl: location.pathname }} replace />;
https://reactrouter.com/en/main/route/error-element 
Можно через это сделать.

2024-01-20 22:59 UTC, DmitriiNazimov commented on src/pages/ArticleDetailsPage/ArticleDetailsPage.jsx
> +    return <Navigate to="/*" state={{ originalUrl: location.pathname }} replace />;
На корневом руте добавить errorElement

2024-01-28 16:39 UTC, DmitriiNazimov requested changes

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/app/App.jsx
>  import routs from 'config/routeConfig/routeConfig';
routes

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/app/App.jsx
> +        loader={({ params }) => {
Копипаста. Нарушение принципа DRY.

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/app/App.jsx
> +        loader={({ params }) => {
Копипаста. Нарушение принципа DRY.

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/app/App.jsx
> +          <Suspense fallback={<Spinner positionCenter />}>
Копипаста. Нарушение принципа DRY.

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/app/App.jsx
> +          <Suspense fallback={<Spinner positionFixedCenter />}>
Копипаста. Нарушение принципа DRY.

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/index.jsx
> +  i18n.changeLanguage(Locales.ru);
Тут коммент нужен почему русский принудительно ставится. Вариант "потому что ты так сказал" не подходит.

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/index.jsx
> +  const rootElemError = document.createElement('div');
Нейминг rootElemError - намекает что там будет сообщение об ошибке. А там все приложение будет.

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/app/App.jsx
> +          <Suspense fallback={<Spinner positionCenter />}>
Уже есть suspense в layout. Тут точно нужен еще один?

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/pages/ArticleDetailsPage/ArticleDetailsPage.async.jsx
> +export const ArticleDetailsPageAsync = lazy(() => import('./ArticleDetailsPage'));
А нельзя в lazy обернуть прямо в компоненте чтобы обойтись без лишних прокладок?

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/pages/ArticleDetailsPage/ArticleDetailsPage.jsx
> -      <Helmet>
Тайтл пропал при прямом заходе на https://dmitriinazimov.github.io/landing/article/1/

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +    document.documentElement.dataset.page = 'article';
Почему article? Зачем это вообще?

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +    const rootElement = document.getElementById('root');
Обходишь тут фреймворк делая поиск через getElementById.

2024-01-28 16:39 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +    const rootElement = document.getElementById('root');
У тебя уже есть rootElem в index.js

2024-01-31 19:20 UTC, AleksKostin commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +    document.documentElement.dataset.page = 'article';
чтобы футер был по центру, как в статьях и услугах, а не на всю ширину

2024-01-31 19:20 UTC, AleksKostin commented on src/index.jsx
> +  const rootElemError = document.createElement('div');
Изменил

2024-01-31 19:21 UTC, AleksKostin commented on src/app/App.jsx
>  import routs from 'config/routeConfig/routeConfig';
Изменил

2024-01-31 19:47 UTC, DmitriiNazimov commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +    document.documentElement.dataset.page = 'article';
Может в футере стили какие прописать? Тут явно какой-то костыль.

2024-02-02 10:51 UTC, AleksKostin commented on src/index.jsx
> +  i18n.changeLanguage(Locales.ru);
Т.к у нас в проекте подключен React snap страницы нашего приложения генерятся статически предварительно с использованием виртуального браузера, где по-умолчанию установлен язык en, и чтобы избежать "мигания" тайтла с en на ru во вкладке страницы мы принудительно ставим ru, при этом "мигание" сохранится при переключении на язык en. Этого можно было бы избежать при использовании SSR

2024-02-02 10:52 UTC, AleksKostin commented on src/app/App.jsx
> +          <Suspense fallback={<Spinner positionCenter />}>
Урал

2024-02-02 10:53 UTC, AleksKostin commented on src/app/App.jsx
> +        loader={({ params }) => {
Вынес в отдельную функцию

2024-02-02 10:58 UTC, AleksKostin commented on src/pages/ArticleDetailsPage/ArticleDetailsPage.async.jsx
> +export const ArticleDetailsPageAsync = lazy(() => import('./ArticleDetailsPage'));
Можно. Но я воспользовался принципом из подхода FSD из курса Ulbi где lazy компоненты вынесены отдельно. Если нужно могу переделать

2024-02-02 12:33 UTC, AleksKostin commented on src/app/App.jsx
> +        loader={({ params }) => {
Вынес в отдельную функцию

2024-02-12 20:25 UTC, DmitriiNazimov commented on package.json
> +    "postbuild": "react-snap --wait=5000",
Это для чего?

2024-02-12 20:25 UTC, DmitriiNazimov commented on src/app/App.jsx
> +    const currentItem = data.find((item) => (
В одну строку можно: const currentItem = data.find((item) => item.id === id);

2024-02-12 22:59 UTC, AleksKostin commented on package.json
> +    "postbuild": "react-snap --wait=5000",
удалил

2024-02-12 22:59 UTC, AleksKostin commented on src/app/App.jsx
> +    const currentItem = data.find((item) => (
сделал

2024-02-18 10:00 UTC, AleksKostin commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +    const rootElement = document.getElementById('root');
Экспортировал rootElement из index.js

2024-02-18 10:03 UTC, DmitriiNazimov approved these changes

2024-02-18 10:04 UTC, merged