feat: add ServicesPage, ServiceWrapper; update MainPage
AleksKostin/t-ende-landing-page pull request #2
Opened 2023-09-18 01:14 UTC by AleksKostin

Добавил вторую страницу ServicesPage. Добавил ServiceWrapper для динамического отображения услуг на странице. Обновил MainPage в части анимации скрола по нажатию на стрелку, добавил иконки мессенджеров.

2023-09-18 19:54 UTC, DmitriiNazimov requested changes

2023-09-18 19:54 UTC, DmitriiNazimov commented on public/icons/instagram.svg
Дизайнер говорит что исправила иконку.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/assets/icons/circle-160-160.svg
Это можно сделать css-свойствами обычному div. 
Border radius: 100% + border: solid 1px someColor.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +  background: #FEFFFF;
Цвета лучше выносить в переменные.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    color: rgb(0 0 0 / 80%);
Цвета лучше чтобы были указаны в едином формате, а не так что где-то rgba, где-то #fff, где-то #f0f0f0 и т.д. 
Прозрачность можно регулировать через свойство opacity.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    transform: perspective(1px) scale(1.01);
А perspective(1px) точно нужно? Ни разу не сталкивался на практике.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.jsx
> +                  alt={contact.icon.match(/[^\/]+(?=\.\w+$)/)[0]}
Регулярку лучше положить в переменную с человекопонятным именем.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.scss
> +  &__hover {
Я тут сломался на hover>hover. Точно нужно создавать класс с именем hover?

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.scss
> +  &__hover {
Вообще здесь что-то не так пошло с неймингом. "__" - это выделение элемента. Но "loaded" и "hover" - это не элемент, а модификатор. Модификаторы выделяются одинарным подчеркиванием.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.jsx
> +        <h1 id="services-page" className="services-page__title">
На странице не может быть несколько тегов H1. 1 страница - 1 H1.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.scss
> +  height: 1127px;
А зачем фиксированная высота? Выглядит как косяк.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.scss
> +  overflow: hidden;
А зачем overflow? Кажется, тут не подразумевается чтобы что-то вылезало за границы.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.scss
> +  background-color: #F8FCFD;
Цвета лучше в переменные.

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.scss
> +.services-page {
Может просто ".services"?

2023-09-18 19:54 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +.service-wrapper {
Кажется логичнее было бы ".service-item" или просто ".service".

2023-09-18 19:57 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.jsx
> +            <div className="services-page__content__block">
Это какой-то селектор курильщика :) Нельзя в одном селекторе дважды использовать двойное подчеркивание. Непонятно зачем вообще этот селектор нужен если на него не повешены стили.

2023-10-07 10:05 UTC, DmitriiNazimov requested changes

2023-10-07 10:05 UTC, DmitriiNazimov commented on src/app/styles/variables/global.scss
> +  --service-item-height: 366px;
C переменными отступов какая-то беда. Не должно быть переменных под конкретные элементы/классы. 
Должны быть универсальные переменные типа: (единицы измерения не обязательно rem)
    --gap-tiny: 0.5rem;
    --gap-min: 1rem;
    --gap-small: 1.5rem;
    --gap-medium: 2rem;
    --gap-big: 3rem;
    --gap-huge: 4rem;
    
И по месту их подставляешь. Если в каком-то месте нужно что-то уникальное, типа 366px, то под это переменную создавать не надо.

Переменные нужны для не уникальных значений и для стандартизации отступов на проекте.

2023-10-07 10:05 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.jsx
> +            <div className="services__content-block" key={block.id}>
Зачем нужен div services__content-block если на него не повешены никакие стили?

2023-10-07 10:05 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
>    border-radius: 5px;
border-radius тоже можно вынести в переменные, или можно использовать переменные для отступов. Ведь наверное в разных элементах проекта будет указываться одинаковый border-radius?

2023-10-07 10:05 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    color: #000;
Захардкодил цвет + поменял его через opacity, в итоге хз какой цвет получился. 
Наверное такой цвет не в одном месте проекта используется? Тогда надо вынести в переменную и либо прописать конкретный цвет типа "#181919", либо через rgba(0, 0, 0, 0.9)

2023-10-07 15:32 UTC, DmitriiNazimov requested changes

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +  opacity: 0;
Лучше display:none; 
Opacity делает элемент прозрачным, но он остается на странице, на него можно нажимать, он занимает место.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.jsx
> +      refInput.current.click();
А клик для чего? Чтобы менять состояние чекбокса checked|not checked? Так может и менять ему напрямую это значение? `refInput.current.checked = false`
Вообще не очень понял зачем тут такой огород городить. Кажется проще и практичнее было бы сделать бургеру position: fixed и тогда он бы всегда был у юзера на экране и не нужен был бы весь этот код. Не нужно было бы зависимость тащить.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +  &__btn > span,
Не надо вешать стили на теги, даже если кажется "ну тут то можно". Лучше добавить класс.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +    visibility: hidden;
Почему именно visibility?

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.scss
> +    right: 13px;
Хотелось бы чтобы отступы были стандартизированы и указаны через переменные. Здесь точно надо именно 13? Стандарнтый 15 не подойдет? И так по всему проекту.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.jsx
>          <img src={content.icon} alt="" />
Alt надо либо прописать, либо убрать.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.jsx
>    const { t } = useTranslation();
Имя файла наверное надо переименовать в ServiceItem

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    border: solid 2px #E8BD67;
Цвет надо в переменную.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
>    color: inherit;
Цвет надежнее указать точно.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    color: #000;
См. предыдущий коммент про цвет #000

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
>      letter-spacing: 0.16px;
В разных местах используется разный letter-spacing. Это точно необходимо?

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +@media (width < 1310px) {
Почему 1310, а не 1280?
1280 - это стандартное разрешение у многих юзеров.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    width: 490px;
А точно надо фиксированные размеры задавать в пикселях? Кажется лучше было бы в процентах, и при этом ограничить максимальный и минимальный размер (через min|max-width или через clamp).

Вообще что-то тут пошло не так в целом. Думаю стоит создать такие медиа:
- width > 1280px
- width > 1024px и width < 1280px
- width > 620 width < 1024px
- width < 620

И под каждый размер прописать свои правила min|max-width или clamp.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +  .service-item__image img{
Не надо стили на теги.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    font-size: 14px;
Может в переменные положить размер шрифта?

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.scss
>      &:hover {
&__image:hover {

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.scss
> +    border: 1px solid rgba(0, 0, 0, 80%);;
Двойные точка с запятой. 
И я убрал коммент и у меня не светятся ошибки. Коммент точно нужен?

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.scss
> +    font-size: 1.3rem;
Где-то в пикселях, где-то в rem. Лучше выбрать какие-то одни единицы измерения. И сделать переменные.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.scss
> +    width: 140px;
У тебя много где размер элементов задан жестко в пикселях. В целом это не очень хорошая практика. Лучше когда элементы имеют плавающий размер. Можно им ограничивать максимальный и минимальный размер при этом, если надо.

2023-10-07 15:32 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.scss
> +@media (width < 1030px) {
Почему 1030, а не 1024?

2023-10-10 23:16 UTC, AleksKostin commented on src/pages/ServicesPage/ServicesPage.jsx
> +            <div className="services__content-block" key={block.id}>
https://github.com/AleksKostin/t-ende-landing-page/blob/af901ce648fba64eab6370a68f7707de9fe3a703/src/pages/ServicesPage/ServicesPage.scss#L30

https://github.com/AleksKostin/t-ende-landing-page/blob/af901ce648fba64eab6370a68f7707de9fe3a703/src/pages/ServicesPage/ServicesPage.scss#L38

здесь в двух местах я использую этот класс для работы с отступами

2023-10-10 23:32 UTC, AleksKostin commented on src/components/Navbar/Navbar.jsx
> +      refInput.current.click();
В макете дизайнера не было обозначено position: fixed для бургер-меню. Поэтому добавил автоматическое закрытие при скролле и при открытом бургер-меню, когда он покидает viewport. 
Заменил клик на  refInput.current.checked = false, но принципиального отличия в этом не увидел от клика, результат один и тот же.

2023-10-10 23:36 UTC, AleksKostin commented on src/app/styles/variables/global.scss
> +  --service-item-height: 366px;
Учту и исправлю

2023-10-10 23:39 UTC, AleksKostin commented on src/components/ServiceWrapper/ServiceWrapper.scss
>    border-radius: 5px;
еще в карточках статей указан такой же радиус, добавлю в переменную

2023-10-10 23:40 UTC, AleksKostin commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    color: #000;
Исправлю

2023-10-10 23:41 UTC, AleksKostin commented on src/components/Navbar/Navbar.scss
> +  opacity: 0;
Исправлю

2023-10-10 23:42 UTC, AleksKostin commented on src/components/Navbar/Navbar.scss
> +  &__btn > span,
Переделаю на класс

2023-10-10 23:48 UTC, AleksKostin commented on src/components/Navbar/Navbar.scss
> +    visibility: hidden;
по другому просто не получается, c display none не работает

2023-10-10 23:51 UTC, AleksKostin commented on src/components/Navbar/Navbar.scss
> +    right: 13px;
можно и 15. выравнивал ссылки в бургер-меню относительно Х и 13 на мой взгляд было норм.

2023-10-10 23:51 UTC, AleksKostin commented on src/components/ServiceWrapper/ServiceWrapper.jsx
>          <img src={content.icon} alt="" />
Исправлю

2023-10-10 23:55 UTC, AleksKostin commented on src/components/ServiceWrapper/ServiceWrapper.jsx
>    const { t } = useTranslation();
изначально все было названо service wrapper, после замечания [тут](https://github.com/AleksKostin/t-ende-landing-page/pull/2#discussion_r1329205851) в предыдущем коммите, изменил на service item. Исправлю

2023-10-10 23:56 UTC, AleksKostin commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +    border: solid 2px #E8BD67;
Добавлю

2023-10-10 23:56 UTC, AleksKostin commented on src/components/ServiceWrapper/ServiceWrapper.scss
>    color: inherit;
Укажу

2023-10-10 23:57 UTC, AleksKostin commented on src/components/ServiceWrapper/ServiceWrapper.scss
>      letter-spacing: 0.16px;
все latter-spacing беру из макета дизайнера

2023-10-11 00:11 UTC, AleksKostin commented on src/components/ServiceWrapper/ServiceWrapper.scss
> +  .service-item__image img{
исправлю

2023-10-11 06:38 UTC, DmitriiNazimov commented on src/pages/ServicesPage/ServicesPage.jsx
> +            <div className="services__content-block" key={block.id}>
Может лучше эту работу с отступами сразу в ServiceWrapper делать? Здесь можно уже не переделывать, но в целом, мне кажется, не стоит создавать контейнеры выполняющие незначительные функции, которые можно было бы повесить на потомков.

2023-10-11 06:42 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.jsx
> +      refInput.current.click();
Результат один и тот же, но есть нюанс :) Клик может провоцировать неожиданное поведение в будущем, когда сюда добавится какая-то еще логика. Если нам нужно поменять checked - то нужно использовать для этого соответствующее событие, иначе потом возможны сюрпризы.

2023-10-15 00:10 UTC, AleksKostin commented on src/pages/MainPage/MainPage.scss
> +    border: 1px solid rgba(0, 0, 0, 80%);;
если у меня убрать коммент то вылезает ошибка Expected modern color-function notation (color-function-notation)Stylelint

2023-10-15 08:51 UTC, DmitriiNazimov commented on src/pages/MainPage/MainPage.scss
> +    border: 1px solid rgba(0, 0, 0, 80%);;
Хм, а у меня почему-то нет проблем. Вот тут это правило описано: https://stylelint.io/user-guide/rules/color-function-notation/

Попробуй записать в таком формате: `color: rgb(12 122 231 / 0.2)`

Если не поможет, или не придумаешь как еще записать цвет чтобы не ругалось, то надо отключить это правило. Не дело при упоминаниях цвета писать комменты.

2023-11-03 14:36 UTC, DmitriiNazimov approved these changes

2023-11-03 15:58 UTC, merged