Develop articles page
AleksKostin/t-ende-landing-page pull request #5
Opened 2023-11-19 10:56 UTC by AleksKostin

2023-11-19 11:52 UTC, DmitriiNazimov requested changes

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Arrows/Arrows.scss
> +  z-index: 1;
Желательно z-index хранить в переменных и использовать их. Случайные значения в z-index ведут к багам. В  рамках учебного проекта не обязательно переделывать.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
Может посмотришь как отлючить комменты? Какие-то атрибуты для a11y прописать надо я думаю.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +  } = useContext(SliderContext);
Обоснуй использование контекста, а не стора )

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +  const renderDots = () => {
```javascript
  const dotsItems = [...items].map((item, i) => (
    <div
      key={`dot-${i}`}
      className={`dot ${i === currentSlide ? 'selected' : ''}`}
    />
  ));
```

Так вроде поизящнее получается. Вроде тут можно даже и не создавать новый массив, а напрямую использовать items. Но возможно это приведет к лишним ререндерам. В Свелте таких проблем нет )

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +    items,
Тут бы TS заюзать. Непонятно items это массив, объект, или может вообще строка через запятую.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +          key={`dot-${i}`}
Использовать индекс в массиве как ключ - это плохо. Массив может поменяться и будет работать неправильно.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +    <div className="dots">{renderDots()}</div>
Нейминг renderDots мне не нравится. Функция же не рендерит, а возвращает данные которые Реакт отрендерит. Тогда что-то типа getDots должно быть.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +          className={`dot ${i === currentSlide ? 'selected' : ''}`}
У тебя же подключена classnames (cn()), используй ее.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Dots/Dots.scss
> +  bottom: 18px;
Вот надо заканчивать так верстать. Не должно быть такого что ты попиксельно подгоняешь элемент повыше/пониже. Нужно использовать flexbox. Может в данном случае дополнительную обертку стоит сделать.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Navbar/Navbar.jsx
>            <a href="#1" className="header__link">
А тут не надо поменять?

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Slide/Slide.jsx
> +  const { data } = props;
А если нету data в пропсах? Или она есть, но в ней нет каких-то полей. Тут бы типизацию, или проверки какие-то.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/Slide/Slide.scss
> +    margin-top: 5px;
У тебя 5px в разных margin используется - надо вынести в переменную.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/components/SlidesList/SlidesList.jsx
> +    <div className={classNames('slide-list', animation)}>
cn() короче

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +      background: #E8BD67;
В переменную

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +      margin-right: 30px;
--gap-small

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +    opacity: 0.8;
Опять управление цветом через opacity?

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +    padding: 60px 0;
--gap-medium

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +    margin-bottom: 30px;
--gap-small

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +    margin-bottom: 30px;
--gap-small

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +    font-size: 20px;
--font-size-l

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +      background: #E8BD67;
--line-color

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +      margin-right: 15px;
--gap-min

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/AboutPage/AboutPage.scss
> +    margin-top: 15px;
--gap-min
  Нужен робот который будет тебя током бить за такое каждый раз )

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +  const [itemsDisplayed, setItemsDisplayed] = useState(3);
Я уже не помню что там говорят реактовские best practicies, но кажется что простыня из useState - это не очень. По хорошему тут уже Store надо использовать. Где все эти данные будут отдельными полями единого хранилища. 

Думаю здесь бы подошел useReducer(). И контекст тогда не нужен будет. Знал бы ты насколько это все проще на Свелте )

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +    const media = window.matchMedia('(max-width: 1024px)');
Круто, теперь я знаю про matchMedia. Но я не понял зачем он здесь, кажется можно было бы сделать то же самое через CSS.

2023-11-19 11:52 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +                      {t('showMore')}
При клике на кнопку появляется новая карточка, но ее может быть не видно, или она может быть сильно обрезана нижним краем экрана. Нужно чтобы сколлило к новой карточке, чтобы она становилась по центру экрана.

2023-11-19 12:26 UTC, AleksKostin commented on src/components/Arrows/Arrows.scss
> +  z-index: 1;
Ок, в будущем буду делать так

2023-11-19 12:27 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
Посмотрю, поправлю

2023-11-19 12:28 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +  } = useContext(SliderContext);
Чтобы не прикидывать большое количество пропсов, решил использовать контекст

2023-11-19 12:32 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +  } = useContext(SliderContext);
Это понятно. Но почему контекст, а не стор?

2023-11-19 12:38 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +  const renderDots = () => {
Реакт умный, думаю, что в моем варианте, что в твоем должно быть одинаковое количество ререндоров, мы же не зря задаем атрибут key, он должен будет в своем виртуальным доме вычислить какой элемент изменяется и сделать только его ререндер

2023-11-19 12:40 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +    items,
Я тоже иногда хочу использовать ТS, для пропсов, но для быстроты разработки мы решили делать сайт на JS

2023-11-19 12:40 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +      margin-right: 15px;
Глаз замыливается и не все замечаю

2023-11-19 12:45 UTC, AleksKostin commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +  const [itemsDisplayed, setItemsDisplayed] = useState(3);
Реакт для небольшого проекта все таки многословен, согласен. С твоего позволения я бы не стал сейчас переписывать код на использование стора)

Уже посмотрел ролик сравнения кода на реакте и на свелте, и в некоторых моментах он действительно магически работает)

2023-11-19 12:48 UTC, AleksKostin commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +    const media = window.matchMedia('(max-width: 1024px)');
Мне нужно полностью отключать код слайдера и заменить его на простой массив, с помощью СSS это можно сделать через display none, но я решил такой способ попробовать) Вообще для этого у реакта есть библиотека react responsive.

2023-11-19 12:48 UTC, AleksKostin commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +                      {t('showMore')}
Сделаю скролл

2023-11-19 13:55 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +  } = useContext(SliderContext);
Т.к. эти пропсы нужны только в ArticlesPage и больше нигде не используются, а стор я бы использовал если бы эти данные требовались бы в других местах приложения. Т.е. контекст для изолированных компонентов, стор для общего пользования данными.

2023-11-19 13:57 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +          key={`dot-${i}`}
Знаю. Переделаю

2023-11-19 13:57 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +    <div className="dots">{renderDots()}</div>
Переменую

2023-11-19 13:59 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +          className={`dot ${i === currentSlide ? 'selected' : ''}`}
Ок

2023-11-19 13:59 UTC, AleksKostin commented on src/components/Dots/Dots.scss
> +  bottom: 18px;
Переделаю

2023-11-19 14:02 UTC, AleksKostin commented on src/components/Navbar/Navbar.jsx
>            <a href="#1" className="header__link">
Все ссылки хотел рефакторить уже на последнем этапе разработки , когда все страницы будут готовы. Это пока шаблон

2023-11-19 14:03 UTC, AleksKostin commented on src/components/Slide/Slide.jsx
> +  const { data } = props;
Типизация мастхэв. Сделаю проверки

2023-11-19 14:03 UTC, AleksKostin commented on src/components/Slide/Slide.scss
> +    margin-top: 5px;
Ок

2023-11-19 14:06 UTC, AleksKostin commented on src/components/SlidesList/SlidesList.jsx
> +    <div className={classNames('slide-list', animation)}>
В библиотеке classNames https://github.com/JedWatson/classnames

2023-11-19 14:10 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +    opacity: 0.8;
Это старая верстка еще. Поменяю в ПР AboutPage

2023-11-19 14:10 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +      background: #E8BD67;
Поменяю в ПР AboutPage

2023-11-19 14:10 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +      margin-right: 30px;
Поменяю в ПР AboutPage

2023-11-19 14:10 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +    padding: 60px 0;
Поменяю в ПР AboutPage

2023-11-19 14:10 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +    margin-bottom: 30px;
Поменяю в ПР AboutPage

2023-11-19 14:10 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +    margin-bottom: 30px;
Поменяю в ПР AboutPage

2023-11-19 14:11 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +    font-size: 20px;
Поменяю в ПР AboutPage

2023-11-19 14:11 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +      background: #E8BD67;
Поменяю в ПР AboutPage

2023-11-19 14:11 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +    margin-top: 15px;
Поменяю в ПР AboutPage

2023-11-19 14:11 UTC, AleksKostin commented on src/pages/AboutPage/AboutPage.scss
> +      margin-right: 15px;
Поменяю в ПР AboutPage

2023-11-19 17:58 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +                  {items.map((item, index) => {
Зависит от код-стайла, но лично мне тяжеловато читать циклы прямо в простыне JSX. Я бы такие штуки выносил в отдельные переменные до return, а здесь просто вставлял.

2023-11-19 18:02 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +  } = useContext(SliderContext);
Почитай про контекст, у него есть недостатки и его стараются не использовать по возможности.

2023-11-19 18:05 UTC, DmitriiNazimov commented on src/components/Dots/Dots.jsx
> +          key={`dot-${i}`}
```javascript
function generateUniqueKey() {
    // Генерируем случайное число от 0 до 1 и преобразуем его в строку с radix 36
    // для получения уникального ключа в виде строки
    return Math.random().toString(36).substring(2);
}

// Пример использования
const uniqueKey = generateUniqueKey();
console.log(uniqueKey);
```

Как вариант.

2023-11-19 18:10 UTC, DmitriiNazimov commented on src/components/SlidesList/SlidesList.jsx
> +    <div className={classNames('slide-list', animation)}>
```
import cn from 'classnames';
```
Нормально работает, я проверил.

2023-11-19 18:11 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +  const [itemsDisplayed, setItemsDisplayed] = useState(3);
Ок.

2023-11-20 21:14 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +          key={`dot-${i}`}
там проще можно. в items есть ключ id
key={items[i].id}

2023-11-20 21:15 UTC, AleksKostin commented on src/components/SlidesList/SlidesList.jsx
> +    <div className={classNames('slide-list', animation)}>
с этого файла и далее перейду на cn

2023-11-20 21:20 UTC, AleksKostin commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +                  {items.map((item, index) => {
Да, в плане чтения кода есть неудобство. Но работает же)) А так вынесу в отдельную функцию

2023-11-20 21:27 UTC, AleksKostin commented on src/components/Dots/Dots.jsx
> +  } = useContext(SliderContext);
Прочитал, спасибо за наводку. Основной тезис не в защиту контекста - это "все, что использует контекст, перерендеривается каждый раз, когда контекст изменяет состояние". В нашем проекте это, думаю, не критично, но в большом проекте это уже может сыграть злую шутку. На будущее учту это!

2023-12-03 10:37 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +                      {t('showMore')}
Скролл не появился

2023-12-05 06:19 UTC, DmitriiNazimov commented on src/components/Spinner/Spinner.jsx
> +const Spinner = ({ cls }) => (
Что такое cls?

2023-12-05 06:21 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +          ref={index === itemsDisplayed - 1 ? newSlideRef : null}
👍

2023-12-05 06:23 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +  const dataSliderContext = useMemo(
А тут точно нужен useMemo если у него столько зависимостей?

2023-12-05 06:25 UTC, DmitriiNazimov commented on src/pages/ArticlesPage/ArticlesPage.scss
> +.hidden {
Наверное логичнее этот класс положить на уровне приложения, он же может использоваться не только в ArticlesPage.

2023-12-05 21:41 UTC, AleksKostin commented on src/components/Spinner/Spinner.jsx
> +const Spinner = ({ cls }) => (
Хотел с помощью этого пропса накидывать класс с position fixed по центру окна что бы при первой загрузке сайта в Suspense в App.js. Переименую этот пропс для читабельности в positionFixedCenter

2023-12-05 22:06 UTC, AleksKostin commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +  const dataSliderContext = useMemo(
Линтер требует) Как понял, просит избежать создания новых ссылок после каждого ререндера
 
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-constructed-context-values.md

2023-12-05 22:08 UTC, AleksKostin commented on src/pages/ArticlesPage/ArticlesPage.jsx
> +  const dataSliderContext = useMemo(
Если не добавлять зависимости но ругается https://github.com/facebook/react/issues/14920

2023-12-05 22:10 UTC, AleksKostin commented on src/pages/ArticlesPage/ArticlesPage.scss
> +.hidden {
Перенесу

2023-12-06 06:44 UTC, DmitriiNazimov commented on src/components/Slide/Slide.jsx
> +    setIsLoaded(() => true);
А почему, кстати, setIsLoaded(() => true);, а не setIsLoaded(true);?

2023-12-06 06:46 UTC, DmitriiNazimov commented on src/components/Slide/Slide.jsx
> +    setIsLoadedSlide(() => true);
Я до конца не уловил зачем нам оба setIsLoaded и setIsLoadedSlide?

2023-12-06 06:48 UTC, DmitriiNazimov approved these changes

2023-12-06 21:14 UTC, AleksKostin commented on src/components/Slide/Slide.jsx
> +    setIsLoadedSlide(() => true);
setIsLoaded при первой загрузке слайда, setIsLoadedSlide срабатывает в момент переключения слайда в changeSlide в ArticlesPage

2023-12-11 09:35 UTC, merged